# -*- coding: utf-8 -*-

import AnalizadorLexico as s
from ComponentesLexicos import *

TAS = {
    (PROGRAMA, id): [FUNCION, OTRAFUNCION],
    (OTRAFUNCION, id): [FUNCION, OTRAFUNCION],
    (OTRAFUNCION, peso): [epsilon],
    (FUNCION, id): [id, parentesisAbre, PARAMETROS, parentesisCierra, CUERPO],
    (PARAMETROS, id): [PARAMETRO],
    (PARAMETROS, parentesisCierra): [epsilon],
    (PARAMETRO, id): [id, OTROPARAMETRO],
    (OTROPARAMETRO, coma): [coma, id, OTROPARAMETRO],
    (OTROPARAMETRO, parentesisCierra): [epsilon],
    (CUERPO, llaveAbre): [llaveAbre, LISTASENTENCIAS, llaveCierra],
    (LISTASENTENCIAS, id): [SENTENCIA, puntoycoma, LISTASENTENCIAS],
    (LISTASENTENCIAS, leer): [SENTENCIA, puntoycoma, LISTASENTENCIAS],
    (LISTASENTENCIAS, escribir): [SENTENCIA, puntoycoma, LISTASENTENCIAS],
    (LISTASENTENCIAS, si): [SENTENCIA, puntoycoma, LISTASENTENCIAS],
    (LISTASENTENCIAS, mientras): [SENTENCIA, puntoycoma, LISTASENTENCIAS],
    (LISTASENTENCIAS, llaveCierra): [epsilon],
    (SENTENCIA, id): [ASIGNACION],
    (SENTENCIA, leer): [LECTURA],
    (SENTENCIA, escribir): [ESCRITURA],
    (SENTENCIA, si): [CONDICIONAL],
    (SENTENCIA, mientras): [CICLO],
    (ASIGNACION, id): [id, igual, Q, H, N],
    (CONDICIONAL, si): [si, parentesisAbre, CONDICION, parentesisCierra, CUERPO, SINO],
    (SINO, sino): [sino, CUERPO],
    (SINO, puntoycoma): [epsilon],
    (CICLO, mientras): [mientras, parentesisAbre, CONDICION, parentesisCierra, CUERPO],
    (LECTURA, leer): [leer, parentesisAbre, cadena, coma, id, parentesisCierra],
    # de acá para abajo faltan actualizar y agregar los restantes, lo mismo con los componentes léxicos
    (ESCRITURA, escribir): [escribir, parentesisAbre, cadena, coma, Q, H, N, parentesisCierra],
    (CONDICION, verdadero): [verdadero],
    (CONDICION, falso): [falso],
    (N, puntoycoma): [epsilon],
    (N, parentesisCierra): [epsilon],
    (N, mas): [mas, Q, H, N],
    (N, menos): [menos, Q, H, N],
    (H, puntoycoma): [epsilon],
    (H, parentesisCierra): [epsilon],
    (H, mas): [epsilon],
    (H, menos): [epsilon],
    (H, por): [por, Q, H],
    (H, dividido): [dividido, Q, H],
    (Q, parentesisAbre): [parentesisAbre, Q, H, N, parentesisCierra],
    (Q, id): [id],
    (Q, real): [real]
}
